WhoCanHelpMe.Presentation/Controllers/ProfileController.cs
namespace WhoCanHelpMe.Presentation.Controllers
{
    using System;
    using System.Net;
    using System.Web.Mvc;

    using MvcContrib;
    using MvcContrib.Filters;

    using WhoCanHelpMe.ApplicationServices.Command;
    using WhoCanHelpMe.ApplicationServices.Contracts;
    using WhoCanHelpMe.Presentation.ActionFilters;
    using WhoCanHelpMe.Presentation.Models;
    using WhoCanHelpMe.Presentation.Queries;

    public class ProfileController : Controller
    {
        private readonly IBus bus;

        private readonly IViewModelQuery<UpdateProfileViewModel> updateProfileViewModelQuery;

        private readonly IViewModelQuery<ViewProfileViewModel> viewProfileViewModelQuery;

        public ProfileController(
            IBus bus, 
            IViewModelQuery<UpdateProfileViewModel> updateProfileViewModelQuery,
            IViewModelQuery<ViewProfileViewModel> viewProfileViewModelQuery)
        {
            this.bus = bus;
            this.updateProfileViewModelQuery = updateProfileViewModelQuery;
            this.viewProfileViewModelQuery = viewProfileViewModelQuery;
        }

        [HttpGet]
        [ModelStateToTempData]
        public ActionResult Create()
        {
            return this.View(new CreateProfileViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModelStateToTempData]
        [Transaction]
        public ActionResult Create(CreateProfileFormModel formModel)
        {
            if (this.ModelState.IsValid)
            {
                var command = new CreateProfileCommand { UserId = this.User.Identity.Name, Name = formModel.Name };

                this.bus.Send(command);

                return this.RedirectToAction(x => x.Update());
            }

            return this.RedirectToAction(x => x.Create());
        }

        [HttpPost]
        [Authorize]
        [Transaction]
        [ModelStateToTempData]
        public ActionResult AddAssertion(AddAssertionFormModel formModel)
        {
            if (this.ModelState.IsValid)
            {
                var command = new AddAssertionCommand
                    {
                        UserId = User.Identity.Name,
                        CategoryId = formModel.CategoryId,
                        Tag = formModel.Tag
                    };

                this.bus.Send(command);
            }

            return this.RedirectToAction(x => x.Update());
        }

        [HttpPost]
        [Authorize]
        [Transaction]
        public ActionResult DeleteAssertion(Guid assertionId)
        {
            if (this.ModelState.IsValid)
            {
                var command = new DeleteAssertionCommand
                    {
                        UserId = User.Identity.Name,
                        AssertionId = assertionId
                    };

                this.bus.Send(command);
            }

            return this.RedirectToAction(x => x.Update());
        }

        [HttpGet]
        [Authorize]
        [Transaction]
        [ModelStateToTempData]
        public ActionResult Update()
        {
            var viewModel = this.updateProfileViewModelQuery.Get(new { UserId = User.Identity.Name });
            
            if (viewModel == null)
            {
                return this.RedirectToAction(x => x.Create());
            }

            return this.View(viewModel);
        }

        public ActionResult View(Guid id)
        {
            var viewModel = this.viewProfileViewModelQuery.Get(new { ProfileId = id });

            if (viewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return this.View(viewModel);
        }
    }
}

WhoCanHelpMe.Presentation/Controllers/SearchController.cs
namespace WhoCanHelpMe.Presentation.Controllers
{
    using System.Web.Mvc;

    using WhoCanHelpMe.Presentation.Models;
    using WhoCanHelpMe.Presentation.Queries;

    public class SearchController : Controller
    {
        private readonly IViewModelQuery<SearchByTagResultsViewModel> searchByTagQuery;

        public SearchController(IViewModelQuery<SearchByTagResultsViewModel> searchByTagQuery)
        {
            this.searchByTagQuery = searchByTagQuery;
        }

        public ActionResult ByTag(string tagName)
        {
            var viewModel = this.searchByTagQuery.Get(new { tagName });

            return this.View(viewModel);
        }
    }
}

WhoCanHelpMe.Presentation/Controllers/UserController.cs
namespace WhoCanHelpMe.Presentation.Controllers
{
    using System.Security.Authentication;
    using System.Web.Mvc;
    using MvcContrib;

    using NHibernate;

    using WhoCanHelpMe.ApplicationServices.Contracts;

    public class UserController : Controller
    {
        private readonly ISecurityService securityService;

        public UserController(ISecurityService securityService)
        {
            this.securityService = securityService;
        }

        [HttpGet]
        public ActionResult Login(string returnUrl)
        {
            return this.View();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return this.RedirectToAction(x => x.Login(string.Empty));
        }

        public ActionResult Authenticate(string openId, string returnUrl)
        {
            try
            {
                this.securityService.Authenticate(openId);

                if (!string.IsNullOrEmpty(returnUrl))
                {
                    return this.Redirect(returnUrl);
                }

                return this.RedirectToAction<HomeController>(c => c.IndexAsync());
            }
            catch (AuthenticationException ex)
            {
                this.TempData.Add(
                    "Message",
                    ex.Message);

                return this.RedirectToAction(c => c.Login(returnUrl));
            }
        }

        [HttpGet]
        public ActionResult SignOut()
        {
            this.securityService.SignOut();
            return this.RedirectToAction<HomeController>(x => x.IndexAsync());
        }
    }
}

WhoCanHelpMe.Presentation/Views/Shared/_Layout.cshtml
@using WhoCanHelpMe.Presentation.Extensions
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Who Can Help Me?</title>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />

    <link href="~/content/styles/css" rel="stylesheet" type="text/css" media="all" />
    <link href="@Url.Stylesheet("site.less")" rel="stylesheet" type="text/css" media="all" />
    <script src="http://code.jquery.com/jquery-1.7.2.min.js" language="javascript" type="text/javascript"></script>
</head>
<body leftmargin="0" marginwidth="0" topmargin="0" rightmargin="0">
    <div id="container">
        <div id="hdr">
            <div id="hdr_bar">
            </div>
            <div id="hdr_logo">
                <img src="@Url.Image("logo.png")" alt="" height="45" width="623" />
            </div>
            <div id="hdr_strap">
                <p>
                    helping to find people with the skills you need</p>
            </div>
            <div id="hdr_title">
                <h1>@ViewBag.Title</h1>
            </div>
        </div>
        <div id="body">
            <div id="body_content">
                <div>
                    @RenderBody()
                </div>
            </div>
            <div id="body_nav">
                <div id="block-menu-primary-links">
                    <div>
                        <div>
                            @Html.Partial("_Navigation")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="ftr">
        </div>
    </div>
    <script src="~/scripts/js" language="javascript" type="text/javascript"></script>
</body>
</html>

WhoCanHelpMe.Presentation/Views/Shared/_Navigation.cshtml
@using (Html.BeginForm("ByTag","Search", FormMethod.Get)) 
{ 
    @Html.TextBox("tagName", "Search", new { style = "clear: both;", onblur = "if(this.value=='') this.value='Search';", onfocus = "if(this.value=='Search') this.value='';", })
}
<ul>
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("You", "Update", "Profile")</li>
    
    @if (User.Identity.IsAuthenticated)
    {
        <li>@Html.ActionLink("Sign Out", "SignOut", "User")</li>
    }

    <li>@Html.ActionLink("About", "Index", "About")</li>
</ul>

WhoCanHelpMe.Presentation/Views/Shared/_NewsHeadlines.cshtml
@model List<WhoCanHelpMe.Domain.Contracts.NewsItem>
<ol class="statuses" id="timeline">
    @foreach (var newsItem in Model)
    {
        <li class="hentry status">
            <span class="thumb vcard author">
                <a class="tweet-url profile-pic url" href="@newsItem.AuthorUrl">
                    <img height="48" width="48" src="@newsItem.AuthorPhotoUrl" class="photo fn" alt="@newsItem.Author" />
                </a>
            </span> 
            <span class="status-body">
                <strong>
                    <a title="@newsItem.Author" class="tweet-url screen-name" href="@newsItem.AuthorUrl">@newsItem.Author</a>
                </strong> 
                <span class="entry-content">
                    @Html.Raw(newsItem.Headline)
                </span>
            </span>
        </li>
    }
</ol>